# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LXWallet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LXWallet
  pod 'LeexTools'
  pod 'OpenSSL-Universal'
  pod 'SAMKeychain'
  pod 'MBProgressHUD', '0.9.1'
  pod 'Masonry'
  pod 'MJExtension'
end
